### ISSUE TITLE
 bmcs compute image export returns "Unable to process JSON input"

### ISSUE THREAD

**Issue by chowduri** [oracle/bmcs-cli#10]
Hi Below is the command used and the return response. 
bmcs compute image export --image-id "ocid1.image.oc1.xxxxxx" --destination-type '{"objectName": "xxxxx","bucketName": "xxxxx", "namespaceName": "xxxxxx", "destinationType": "objectStorageTuple"}'

ServiceError:
{
    "code": "InvalidParameter",
    "message": "Unable to process JSON input",
    "opc-request-id": "xxxxxxxxxxxxxxx",
    "status": 400
}
 Let me know if I am missing anything here. Thanks in advance.

**Comment by mross22** [comment]
There was a bug in version 2.4.5 of the CLI with the 'bmcs compute image export' command which has since been fixed in version 2.4.6.

Can you please try upgrading your CLI to the latest version (pip install oraclebmc_cli --upgrade) and using the following command to export an image:
`bmcs compute image export to-object`

Note that in the fixed version you can pass in individual parameters instead of the JSON body (you can use the -h or --help parameter to display the usage).

**Comment by chowduri** [comment]
Thanks ... its working fine after upgrading the bmcs version.
